### ISSUE TITLE
RFC: Middleware design

### ISSUE THREAD

**Issue by martndemus** [DockYard/ember-service-worker#25]
# Summary

Managing many Service Worker event handlers isolated from each other will require middleware to effectively handle that.
# Design

A service worker plugin should at least have a `index` module that exports a JavaScript object, that object should have event handlers as properties named after the event that it desires to handler (e.g. `fetch`, `install`). 

Event handler functions should receive the event object as the first argument. Event handlers should return a promise or `undefined`.  Event handlers should not call `waitUntil`, the middleware layer should be responsible for calling `waitUntil` when a event handler returns a promise. This also goes for `fetch` event handlers, they should not call `respondWith` themselves, the middleware should call `respondWith` when one of the `fetch` event handlers' promise resolves to a response.

An example:

``` js
const CACHE_NAME = 'my-cache-v1';
const ASSETS = [
  'index.html',
  '/assets/app.js',
  '/assets/vendor.js',
  '/assets/app.css',
  '/assets/vendor.css'
];

export default {
  install() {
    return caches
      .open(CACHE_NAME)
      .then((cache) => cache.addAll(ASSETS));
  },

  afterInstall() {
    self.skipWaiting();
  },

  fetch(event) {
    return caches.match(event.request, { cacheName: CACHE_NAME });
  }
}
```
### Middleware behaviour

The middleware layer should register one listener for each event using `ServiceWorkerGlobalScope.addEventListener`, when one of those registered listeners is triggered, it should in turn call all other handlers from the modules from the service worker plugins. The behaviour specification per event type is specified below.
#### Activate, Install

The `activate` and `install` handler should execute all handlers at once and then wrap all returned promises by the handlers in a `Promise.all` call and use that promise to call `event.waitUntil`.

Service worker plugins should be able to register a `afterActivate`, `afterInstall` hook. These hooks should be executed after all the main handlers are resolved.

Example simplified implementation of the `install` middleware handler:

``` js
self.addEventListener('install', (event) => {
  let promises = serviceWorkerPlugins.map((plugin) => {
     if (plugin.install) {
        return plugin.install(event);
     }
  });

  event.waitUntil(promises);

  promises.then(() => {
    serviceWorkerPlugins.map((plugin) => {
      if (plugin.afterInstall) {
        plugin.afterInstall();
      }
    });
  });
});
```
#### Fetch

The `fetch` handler should execute all handlers one by one. It should execute one handler, wait for the promise to resolve (if returned), then either call `event.respondWith` if the handler resolves to a response or execute the next hander.

Example simplified implementation of the `fetch` middleware handler:

``` js
self.addEventListener('fetch', (event) {
  let fetchHandlers = serviceWorkerPlugins.reduce((handlers, plugin) => {
     if (plugin.fetch) {
        handlers.push(plugin.fetch);
     }

    return handlers;
  }, []);

  let resolveHandler = (resolve, reject, index) => {
    if (!index) {
      index = 0;
    }

     if (index >= fetchHandlers.length) {
        return;
     }

     fetchHandlers[index](event)
        .then((response) => {
           if (response) {
             return resolve(response);
           } else {
             return resolveHandler(resolve, reject, index + 1);
           }
        })
        .catch(reject);
  };

  new Promise(resolveHandler)
     .then((response) => {
        if (response) {
           event.respondWith(response);
        }
    });
});
```
#### All other events

As far as I know all other events are synchronous and thus the handlers can just be executed one by one, without any promise semantics.

**Comment by nathanhammond** [comment]
- Handlers should be set up as a DAG so that you're able to specify `before` and `after`.
- I'm pretty sure that we want to have a way to specify both sync and async behaviors similar to what was done with ember-prefetch. In other words the middleware needs to be able to communicate back to the SW
  - "You may proceed with other middlewares, but block on this promise before resolving the event."
  - "You shouldn't proceed with other middlewares until this promise resolves."
  - "You should feed the return of my promise into the next middleware." (Think `(req, res)` in `connect` middleware.)

> if the handler resolves to a response or execute the next hand[l]er.
Custom success and failure behaviors see to be missing from the `fetch` proposal. `if (response) {` is far too primitive (and screws up when the response is correctly `falsey`). I feel like each middleware should guaranteedly be run if we're going with the middleware approach unless something directly calls (for example) `res.end()`.

**General**
I'm a bit concerned with how to compose middlewares which I feel like we need to address (and is one of my huge complaints about the `connect` way of approaching things). Head to tail is nice, but making it possible for each to interface with each other gracefully seems like the target we should be aiming for.

**Comment by martndemus** [comment]
> Handlers should be set up as a DAG so that you're able to specify before and after.

Who would be responsible for specifying `before` and `after`, the plugin author, or the consuming app? I'd say the latter, definitely not the former. Plugins themselves should not dictate order in respect to others.

But I think this problem will only manifest itself during the `fetch` event. I might be thinking too simpleton, but I think a simple `['index', 'asset-cache', 'network-first']` in a config file would suffice for that.

> Custom success and failure behaviors see to be missing from the fetch proposal. if (response) { is far too primitive (and screws up when the response is correctly falsey). I feel like each middleware should guaranteedly be run if we're going with the middleware approach unless something directly calls (for example) res.end().

`if (response) { }` can be replaced with `if (response instanceof Response) { }`.
I left out `.catch` scenarios from the examples, but I guess I should start adding `.catch` to them too.
If one fails we should just proceed with the next one.

**Comment by nathanhammond** [comment]
> Who would be responsible for specifying before and after, the plugin author, or the consuming app? I'd say the latter, definitely not the former. Plugins themselves should not dictate order in respect to others.

In Ember CLI land the DAG is set by the addons themselves. There isn't actually a mechanism for the host app to set the addon execution order. This turns out to be fine.

A good measure of your `fetch` implementation is if it can support my [mock SW loading approach](https://gist.github.com/nathanhammond/6f34ac2ec87098512870), do clever things like respond to a MessageChannel message or a Fetch with the same handler (for doing string loading) and more.

All-in-all I think we're a bit early on trying to specify this without just trying things. 😛 As long as we're not afraid to break things, let's just try things with a bit of a random walk for a bit until it stabilizes.
